### ISSUE TITLE
Notifier si flux désactivé

### ISSUE THREAD

**Issue by ddeenniiss** [seenthis/seenthis_importer_flux#3]
J'ai de nouveau le flux RSS qui s'est désactivé pour le compte Etraces.

J'ai juste supprimmé l'étoile devant l'adresse et tout est reparti. Néanmoins, on a mis 4 mois à s'en rendre compte, du coup permettre une notification si le flux est désactivé pourrait-être une chouette fonctionnalité.

**Comment by Fil** [comment]
Normalement le système envoie un mail pour notifier la désactivation. Quelle autre notification pourrait-on envisager ?

**Comment by ddeenniiss** [comment]
Je parlais bien de recevoir une notification par mail.

Pas l'impression d'avoir reçu un mail mais je vérifierais si ça se reproduit.

**Comment by brunob** [comment]
@ddeenniiss oui, on envoie bien un mail dès qu'on désactive le flux, cf #164 :)
