### ISSUE TITLE
seenthis_reactiver_flux : Accès interdit

### ISSUE THREAD

**Issue by Fil** [seenthis/seenthis_importer_flux#5]
Je viens de recevoir une notification par email, avec un lien pour réactiver le flux de @7h36

> https://seenthis.net/spip.php?action=seenthis_reactiver_flux&arg=2358&hash=5d73369d2a28449666cf14274222ee0416008861

Mais quand je clique sur le lien j'obtiens "seenthis_reactiver_flux : Accès interdit"

**Comment by brunob** [comment]
Arf, possible que ça soit un effet de bord des patchs de sécu de la dernière release de SPIP, je regarde ça dès que possible.

**Comment by brunob** [comment]
@Fil je viens de tester en local avec un SPIP à jour et je ne reproduis pas, l'action fait le job (modifications des champs de la table auteurs & redirection vers la page d'accueil).

**Comment by Fil** [comment]
Bizarre!! C'est peut-être parce que j'étais logé sous un autre user ? Ou
bien parce que l'url a pu changer entre le moment où le mail a été émis et
celui où j'ai cliqué ?

>

**Comment by brunob** [comment]
Je viens de tester le lien que tu donnes en exemple (en navigation privée) et je suis bien redirigé sur la page d'accueil (reste à vérifier que l'auteur en question a bien été mis à jour en bdd). J'avais bien modifié l'url du flux de l'auteur en question pour qu'il comporte une * au début, et la modification a bien eu lieu, donc tout semble bien fonctionner :)

On peut fermer ?

**Comment by Fil** [comment]
ça t'alors… on verra bien si le problème se reproduit :)

**Comment by brunob** [comment]
(y)

**Comment by brunob** [comment]
Ça vient de se reproduire, j'ouvre de nouveau cf https://seenthis.net/messages/806406

**Comment by brunob** [comment]
Bon, j'ai testé de nouveau en local, et le lien en question fonctionne bien (même depuis une fenêtre de navigation privée), ça sent le truc de sécu sur le serveur de prod, ou je ne sais quoi d'autre... à suivre.

**Comment by Fil** [comment]
Je viens d'en revalider 2 (rezo et massive), sans souci. En termes d'UX il manque juste un feedback en cas de succès (là on renvoie sur la page d'accueil en cas de succès).

**Comment by brunob** [comment]
Cool que ça fonctionne enfin, je laisse aux autres membres de l'équipe le soin d'améliorer l'ux :)
